export const DISCORD_BOT_MODULE_ID = 'DISCORD_BOT_MODULE_ID';
export const DISCORD_BOT_MODULE_OPTIONS = 'DISCORD_BOT_MODULE_OPTIONS';

export const DiSCORD_SPLIT_MESSAGE_TARGET = 1994;
export const GPT_3_5_CHAR_COUNT = 7090;
export const GPT_3_5_CHAR_URL_COUNT = 2888;
